export const RootActionTypes = {
  
  GET_ROOT_DATA_START: "GET_ROOT_DATA_START",
  GET_ROOT_DATA_SUCCESS: "GET_ROOT_DATA_SUCCESS",
  GET_ROOT_DATA_FAIL: "GET_ROOT_DATA_FAIL",

  GET_FILMS_DATA_START: "GET_FILMS_DATA_START",
  GET_FILMS_DATA_SUCCESS: "GET_FILMS_DATA_SUCCESS",
  GET_FILMS_DATA_FAIL: "GET_FILMS_DATA_FAIL",

  GET_STARSHIPS_DATA_START: "GET_STARSHIPS_DATA_START",
  GET_STARSHIPS_DATA_SUCCESS: "GET_STARSHIPS_DATA_SUCCESS",
  GET_STARSHIPS_DATA_FAIL: "GET_STARSHIPS_DATA_FAIL",

  SET_CUSTOM_ALERT: "SET_CUSTOM_ALERT"

  
};
